name: releaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out code into the Go module directory
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      -
        name: Download GoReleaser
        run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
      -
        name: Run GoReleaser
        run: ./goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
